### ISSUE TITLE
Add explanation on site building process to WIKI

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drupal-au/drupal.org.au#10]
Currently, it is unclear how site changes are delivered to the final build.
This is a blocker for contributors to start working on this.

I propose to use dedicated module with hook_update_N() + config management + features to capture all changes.
CI build would install drupal using `drush si` and would enable `doa_updates` module and would run all `hook_update_N()` functions. Enabling of all contrib and custom modules, as well as config and feature reverts, would be happening there.

Please do suggest another way how to do this if what is described is not suitable.

**Comment by Decipher** [comment]
I agree on the WIKI, and the dedicated module (which is likely to still be a Feature).

As for the approach of enabling the module during CI, I would actually suggest that we use an installation profile so that both CI and users developing locally have a clear path, install the site with this installation profile and that's all you need to do.

Also, as for the naming, while DOA is the unfortunate abbreviation, I don't think we should use it as our machine names, I'd much prefer to standardise on _drupalau_ (drupalau_core, drupalau_theme).

Just my 2c, more opinions preferred.

**Comment by rikki-iki** [comment]
I like the `drupalau_` naming convention too, though DOA does kind of reflect the state of this project lol

Don't much mind about the dedicated module but can't update hooks be done directly in the profile? Whichever approach, we definitely want to document it so people can finally start contributing :)

**Comment by rikki-iki** [comment]
Closing as outdated.
